import {
  Activity, Heart, Stethoscope, Brain, Bone, Baby, Users, Home as HomeIcon, Zap,
  ShieldCheck, Hand, Footprints, Pill, Dumbbell
} from 'lucide-react'

export const SITE_URL = (process.env.NEXT_PUBLIC_BASE_URL || 'https://shriramvidya.in').replace(/\/$/, '')

export const CLINIC = {
  name: 'Shri Ramvidya',
  fullName: 'Shri Ramvidya Electro Acupressure Neuro Therapy & Aayu Pharmacy',
  short: 'Electro Acupressure • Neuro Therapy • Aayu Pharmacy',
  tagline: 'Heal Naturally. Live Pain-Free.',
  phones: ['7300846971', '8601125240', '9161151496'],
  whatsapp: '917300846971',
  email: 'info@shriramvidya.in',
  address: 'Near PNB Bank, Dudhi',
  city: 'Kushinagar',
  region: 'Uttar Pradesh',
  postal: '274403',
  country: 'IN',
  geo: { lat: 26.7406, lng: 83.8881 },
  timings: 'Mon - Sat: 9:00 AM - 8:00 PM | Sun: 9:00 AM - 1:00 PM',
  mapsLink: 'https://maps.app.goo.gl/1m8kyhL8UfGWiZyW8',
  mapsEmbed: 'https://www.google.com/maps?q=PNB+Bank+Dudhi+Kushinagar+Uttar+Pradesh&output=embed',
  experience: '15+',
  social: { facebook: '', instagram: '', youtube: '' },
}

export const IMG = {
  hero: 'https://images.pexels.com/photos/20860622/pexels-photo-20860622.jpeg',
  clinic: 'https://images.unsplash.com/photo-1717500250573-a76fce75ffb3',
  back: 'https://images.pexels.com/photos/5794053/pexels-photo-5794053.jpeg',
  knee: 'https://images.pexels.com/photos/11716938/pexels-photo-11716938.jpeg',
  elderly: 'https://images.unsplash.com/photo-1581090122319-8fab9528eaaa',
  sports: 'https://images.pexels.com/photos/6111585/pexels-photo-6111585.jpeg',
  shoulder: 'https://images.pexels.com/photos/5888099/pexels-photo-5888099.jpeg',
}

export const SERVICES = [
  { slug: 'back-pain', title: 'Back Pain Treatment', icon: Bone, image: IMG.back,
    short: 'Relief from chronic and acute back pain through acupressure and electro therapy.',
    symptoms: ['Lower back stiffness', 'Sharp shooting pain', 'Muscle spasms', 'Difficulty bending', 'Pain while sitting'],
    causes: ['Poor posture', 'Heavy lifting', 'Sedentary lifestyle', 'Disc problems', 'Age-related changes'],
    benefits: ['Long-term pain relief', 'Improved posture', 'Restored mobility', 'No medication needed', 'Better sleep'],
    process: ['Initial diagnosis & assessment', 'Personalized therapy plan', 'Electro-acupressure sessions', 'Manual therapy & stretches', 'Posture correction guidance'] },
  { slug: 'neck-pain', title: 'Neck Pain Treatment', icon: Activity, image: IMG.shoulder,
    short: 'Cervical spondylosis, tech-neck and chronic neck pain treatment.',
    symptoms: ['Stiff neck', 'Headaches', 'Arm pain', 'Tingling sensation', 'Reduced rotation'],
    causes: ['Prolonged screen use', 'Wrong sleeping posture', 'Cervical spondylosis', 'Stress & tension', 'Injury'],
    benefits: ['Released tension', 'Better posture', 'Reduced headaches', 'Improved sleep', 'Full mobility'],
    process: ['Neck examination', 'Trigger point identification', 'Acupressure on cervical points', 'Gentle stretching', 'Home exercises'] },
  { slug: 'knee-pain', title: 'Knee Pain Treatment', icon: Footprints, image: IMG.knee,
    short: 'Restore knee function for daily walking, stairs and normal life.',
    symptoms: ['Pain on stairs', 'Knee swelling', 'Clicking sound', 'Instability', 'Morning stiffness'],
    causes: ['Osteoarthritis', 'Old injury', 'Overuse', 'Obesity', 'Ligament weakness'],
    benefits: ['Pain-free walking', 'Stronger muscles', 'Surgery avoidance', 'Better mobility', 'Confidence back'],
    process: ['Joint mobility test', 'Inflammation reduction', 'Acupressure & electro therapy', 'Strengthening exercises', 'Lifestyle counseling'] },
  { slug: 'shoulder-pain', title: 'Shoulder & Frozen Shoulder', icon: Hand, image: IMG.shoulder,
    short: 'Frozen shoulder and rotator cuff specialist treatment.',
    symptoms: ['Limited movement', 'Night pain', 'Weakness', 'Difficulty lifting', 'Inability to reach behind back'],
    causes: ['Frozen shoulder', 'Rotator cuff tear', 'Bursitis', 'Diabetes-related stiffness', 'Old injury'],
    benefits: ['Full range of motion', 'Strength recovery', 'Pain elimination', 'Return to activities', 'Better sleep'],
    process: ['Range of motion test', 'Pain relief protocol', 'Mobility restoration', 'Strengthening', 'Maintenance plan'] },
  { slug: 'arthritis', title: 'Arthritis Management', icon: Pill, image: IMG.knee,
    short: 'Manage joint pain naturally without long-term medication.',
    symptoms: ['Joint stiffness', 'Morning pain', 'Swelling', 'Reduced grip', 'Joint warmth'],
    causes: ['Osteoarthritis', 'Rheumatoid arthritis', 'Age', 'Joint wear & tear', 'Genetic factors'],
    benefits: ['Less inflammation', 'Better function', 'Slower progression', 'Active lifestyle', 'Drug-free relief'],
    process: ['Comprehensive joint assessment', 'Anti-inflammation therapy', 'Joint protection education', 'Gentle exercises', 'Long-term care plan'] },
  { slug: 'sports-injury', title: 'Sports Injury', icon: Dumbbell, image: IMG.sports,
    short: 'Recovery from sports and exercise-related injuries.',
    symptoms: ['Acute injury', 'Reduced performance', 'Joint instability', 'Recurring pain', 'Muscle pulls'],
    causes: ['Overuse', 'Wrong technique', 'Inadequate warmup', 'Accidents', 'Imbalanced training'],
    benefits: ['Faster recovery', 'Injury prevention', 'Peak performance', 'Stronger comeback', 'Proper rehab'],
    process: ['Injury assessment', 'Acute pain management', 'Progressive rehab', 'Sport-specific training', 'Return-to-play planning'] },
  { slug: 'stroke-rehab', title: 'Stroke Rehabilitation', icon: Brain, image: IMG.elderly,
    short: 'Neuro therapy to regain movement and independence after stroke.',
    symptoms: ['Weakness on one side', 'Speech issues', 'Balance loss', 'Coordination problems', 'Difficulty walking'],
    causes: ['Stroke', 'Cerebral hemorrhage', 'Brain injury', 'Neurological conditions'],
    benefits: ['Restored mobility', 'Independence', 'Better balance', 'Quality of life', 'Speech recovery'],
    process: ['Neurological assessment', 'Custom rehab plan', 'Daily neuro therapy', 'Family training', 'Progress monitoring'] },
  { slug: 'paralysis', title: 'Paralysis Recovery', icon: Heart, image: IMG.elderly,
    short: 'Progressive neuro-rehab for paralysis patients.',
    symptoms: ['Loss of movement', 'Muscle wasting', 'Spasticity', 'Sensory loss', 'Loss of bladder control'],
    causes: ['Stroke', 'Spinal injury', 'Bell’s palsy', 'Nerve damage', 'GBS'],
    benefits: ['Movement recovery', 'Muscle tone', 'Daily function', 'Hope and progress', 'Family relief'],
    process: ['Detailed evaluation', 'Daily neuro therapy', 'Muscle stimulation', 'Progressive exercises', 'Functional training'] },
  { slug: 'sciatica', title: 'Sciatica Treatment', icon: Zap, image: IMG.back,
    short: 'Targeted acupressure to release sciatic nerve compression.',
    symptoms: ['Leg pain', 'Numbness', 'Tingling', 'Burning sensation', 'Pain from back to foot'],
    causes: ['Herniated disc', 'Spinal stenosis', 'Piriformis syndrome', 'Pregnancy', 'Long sitting'],
    benefits: ['Nerve relief', 'Walking comfort', 'No surgery needed', 'Long-term relief', 'Better sleep'],
    process: ['Sciatic nerve assessment', 'Decompression therapy', 'Acupressure on nerve path', 'Core strengthening', 'Postural correction'] },
  { slug: 'cervical', title: 'Cervical Spondylosis', icon: Stethoscope, image: IMG.shoulder,
    short: 'Manage cervical degeneration with electro-acupressure.',
    symptoms: ['Neck stiffness', 'Headache', 'Arm pain', 'Dizziness', 'Tingling in fingers'],
    causes: ['Age-related changes', 'Disc degeneration', 'Bone spurs', 'Wrong posture', 'Prolonged screen use'],
    benefits: ['Reduced pain', 'Better movement', 'Headache relief', 'Restored function', 'Nerve compression relief'],
    process: ['Cervical X-ray review', 'Pain relief therapy', 'Acupressure protocol', 'Strengthening exercises', 'Ergonomic guidance'] },
  { slug: 'migraine', title: 'Migraine & Headache', icon: Brain, image: IMG.shoulder,
    short: 'Natural headache relief through neuro-pressure points.',
    symptoms: ['Recurring headache', 'Sensitivity to light', 'Nausea', 'Visual aura', 'Throbbing pain'],
    causes: ['Stress', 'Sleep issues', 'Hormonal changes', 'Diet triggers', 'Neck tension'],
    benefits: ['Fewer episodes', 'Less intensity', 'No drug dependency', 'Better quality of life', 'Improved focus'],
    process: ['Trigger identification', 'Acupressure for headache points', 'Stress relief therapy', 'Lifestyle counseling', 'Maintenance therapy'] },
  { slug: 'diabetes', title: 'Diabetes Support', icon: Pill, image: IMG.clinic,
    short: 'Acupressure therapy to support diabetic care.',
    symptoms: ['Tingling in feet', 'Slow healing', 'Fatigue', 'Numbness', 'Foot pain'],
    causes: ['Type 2 diabetes', 'Peripheral neuropathy', 'Poor circulation'],
    benefits: ['Better circulation', 'Nerve health', 'Energy boost', 'Symptom relief', 'Foot health'],
    process: ['Health assessment', 'Pancreas support points', 'Circulation therapy', 'Foot care education', 'Ongoing support'] },
  { slug: 'pediatric', title: 'Pediatric Therapy', icon: Baby, image: IMG.clinic,
    short: 'Gentle acupressure therapy for children with developmental needs.',
    symptoms: ['Delayed development', 'Poor posture', 'Coordination issues', 'Weakness'],
    causes: ['Developmental delay', 'Birth complications', 'Cerebral palsy', 'Other conditions'],
    benefits: ['Better development', 'Strength', 'Confidence', 'Independence', 'Improved milestones'],
    process: ['Child assessment', 'Parent counseling', 'Play-based therapy', 'Home exercises', 'Progress tracking'] },
  { slug: 'geriatric', title: 'Elderly Care', icon: Users, image: IMG.elderly,
    short: 'Compassionate therapy for senior citizens.',
    symptoms: ['Balance issues', 'Joint pain', 'Weakness', 'Fall risk'],
    causes: ['Age-related changes', 'Arthritis', 'Decreased activity'],
    benefits: ['Fall prevention', 'Independence', 'Pain management', 'Quality of life', 'Confidence'],
    process: ['Comprehensive evaluation', 'Safe gentle therapy', 'Balance training', 'Strength building', 'Family support'] },
  { slug: 'home-visit', title: 'Home Visit Therapy', icon: HomeIcon, image: IMG.elderly,
    short: 'Expert acupressure care delivered to your doorstep.',
    symptoms: ['Limited mobility', 'Bed-ridden', 'Post-surgery', 'Elderly care'],
    causes: ['Mobility issues', 'Recent surgery', 'Severe pain', 'Elderly'],
    benefits: ['No travel stress', 'Family present', 'Comfortable setting', 'Same quality care', 'Privacy'],
    process: ['Initial phone consultation', 'Doctor visits home', 'Therapy at home', 'Regular follow-ups', 'Family training'] },
  { slug: 'electro-therapy', title: 'Electro Therapy', icon: Zap, image: IMG.clinic,
    short: 'Modern electrotherapy for pain and faster healing.',
    symptoms: ['Acute pain', 'Inflammation', 'Muscle spasm', 'Slow healing'],
    causes: ['Injury', 'Surgery', 'Chronic conditions', 'Muscle disorders'],
    benefits: ['Pain relief', 'Faster healing', 'Reduced inflammation', 'Non-invasive', 'Drug-free'],
    process: ['Condition assessment', 'Electrode placement', 'Customized current', 'Multiple sessions', 'Progress evaluation'] },
  { slug: 'manual-acupressure', title: 'Manual Acupressure', icon: Hand, image: IMG.back,
    short: 'Pressure point techniques to release tension and pain.',
    symptoms: ['Tight muscles', 'Joint stiffness', 'Chronic pain', 'Reduced motion'],
    causes: ['Stress', 'Overuse', 'Tension', 'Poor posture'],
    benefits: ['Instant relief', 'Better mobility', 'Drug-free', 'Lasting results', 'Relaxation'],
    process: ['Body assessment', 'Pressure point therapy', 'Manual techniques', 'Relaxation', 'Self-care guidance'] },
  { slug: 'neuro-therapy', title: 'Neuro Therapy', icon: Brain, image: IMG.elderly,
    short: 'Advanced neuro therapy for nerve-related disorders.',
    symptoms: ['Numbness', 'Weakness', 'Nerve pain', 'Tingling'],
    causes: ['Nerve compression', 'Diabetes', 'Stroke', 'Injury'],
    benefits: ['Nerve recovery', 'Strength return', 'Function restored', 'Less pain', 'Independence'],
    process: ['Neurological exam', 'Nerve mapping', 'Targeted therapy', 'Progressive recovery', 'Long-term support'] },
]

export const TESTIMONIALS = [
  { name: 'Rajesh Yadav', rating: 5, text: 'After years of back pain, Shri Ramvidya acupressure therapy gave me relief in just 3 weeks. No more medicines!', role: 'Farmer, Dudhi' },
  { name: 'Sunita Devi', rating: 5, text: 'My mother had paralysis after stroke. The doctors here brought her back to walking again. Truly blessed!', role: 'Daughter' },
  { name: 'Ankit Singh', rating: 5, text: 'Best clinic in Kushinagar. Frozen shoulder cured completely. Highly professional doctors.', role: 'Businessman' },
  { name: 'Geeta Sharma', rating: 5, text: 'Sciatica was unbearable. After 2 months of treatment, I am completely pain-free. Thank you doctors!', role: 'Homemaker' },
  { name: 'Mukesh Patel', rating: 5, text: 'Affordable, effective and caring team. My knee pain is gone after 15 sessions. Highly recommended.', role: 'Shopkeeper' },
  { name: 'Pooja Verma', rating: 5, text: 'Migraine of 5 years cured with neuro therapy. Could not believe it works so well without medicines.', role: 'Teacher' },
]

export const FAQS = [
  { q: 'What is Electro Acupressure Therapy?', a: 'It is a modern, scientifically-backed therapy that uses gentle electrical stimulation on acupressure points to relieve pain, improve circulation, and accelerate healing — completely drug-free.' },
  { q: 'How many sessions will I need?', a: 'Most patients see significant improvement in 6-10 sessions. Our doctors create a personalized plan after the first consultation.' },
  { q: 'Do you offer home visit therapy?', a: 'Yes! We provide expert home visit therapy across Dudhi, Kushinagar and nearby areas. Book online or call us.' },
  { q: 'Is the treatment painful?', a: 'No. Our therapies are completely painless and relaxing. You will feel only gentle pressure or mild tingling.' },
  { q: 'Do I need a doctor referral?', a: 'No referral needed. Walk in or book an appointment by call/WhatsApp directly.' },
  { q: 'What conditions do you treat?', a: 'We treat back pain, knee pain, sciatica, paralysis, stroke recovery, frozen shoulder, migraine, cervical, arthritis, and many more — all naturally.' },
]

export const TIME_SLOTS = ['09:00 AM', '10:00 AM', '11:00 AM', '12:00 PM', '01:00 PM', '03:00 PM', '04:00 PM', '05:00 PM', '06:00 PM', '07:00 PM']

export const fmtPhone = (p) => p?.length === 10 ? `+91 ${p.slice(0, 5)} ${p.slice(5)}` : p
export const waLink = (msg) => `https://wa.me/${CLINIC.whatsapp}?text=${encodeURIComponent(msg || `Hi, I want to book an appointment at ${CLINIC.name} clinic.`)}`
export const getServiceBySlug = (slug) => SERVICES.find(s => s.slug === slug)

export const buildMetadata = ({ title, description, path = '/', image, keywords }) => {
  const url = `${SITE_URL}${path}`
  return {
    title,
    description,
    keywords,
    alternates: { canonical: url },
    openGraph: {
      title,
      description,
      url,
      siteName: CLINIC.fullName,
      type: 'website',
      images: image ? [{ url: image }] : undefined,
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: image ? [image] : undefined,
    },
  }
}
